const express = require('express');
const authRoutes = require('./authRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const designationRoutes = require('./designationRoutes');
const labourCategoryRoutes = require('./labourCategoryRoutes');
const contractorRoutes = require('./contractorRoutes');
const supervisorRoutes = require('./supervisorRoutes');
const workerRoutes = require('./workerRoutes');
const kycRoutes = require('./kycRoutes');
const attendanceRoutes = require('./attendanceRoutes');
const gateLogRoutes = require('./gateLogRoutes');
const damageRoutes = require('./damageRoutes');
const fineRoutes = require('./fineRoutes');
const accidentRoutes = require('./accidentRoutes');
const advanceRoutes = require('./advanceRoutes');
const overtimeRoutes = require('./overtimeRoutes');
const policyRoutes = require('./policyRoutes');
const holidayRoutes = require('./holidayRoutes');
const reportRoutes = require('./reportRoutes');
const notificationRoutes = require('./notificationRoutes');
const geoRoutes = require('./geoRoutes');
const verificationRoutes = require('./verificationRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/designations', designationRoutes);
router.use('/labour-categories', labourCategoryRoutes);
router.use('/contractors', contractorRoutes);
router.use('/supervisors', supervisorRoutes);
router.use('/workers', workerRoutes);
router.use('/kyc', kycRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/gate-logs', gateLogRoutes);
router.use('/damages', damageRoutes);
router.use('/fines', fineRoutes);
router.use('/accidents', accidentRoutes);
router.use('/advances', advanceRoutes);
router.use('/overtimes', overtimeRoutes);
router.use('/policies', policyRoutes);
router.use('/holidays', holidayRoutes);
router.use('/reports', reportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/geo', geoRoutes);
router.use('/verifications', verificationRoutes);

module.exports = router;
