const { z } = require('zod');
const { optionalString, optionalDate, optionalInt, optionalPassword, emailString, optionalEmailString, digitsString, optionalDigitsString, optionalExactDigitsString } = require('./common');

const contractorSchema = z.object({
  contractorName: z.string().min(1, 'Contractor name is required').max(30),
  establishmentName: optionalString(30),
  contactPerson: z.string().min(1, 'Contact person is required').max(30),
  phone: digitsString(10, 'Phone number must be exactly 10 digits'),
  email: emailString(),
  email2: optionalEmailString(),
  email3: optionalEmailString(),
  email4: optionalEmailString(),
  address: z.string().min(1, 'Address is required'),
  village: optionalString(100),
  taluka: optionalString(100),
  city: optionalString(100),
  state: optionalString(100),
  pincode: optionalExactDigitsString(6, 'Pincode must be exactly 6 digits'),
  aadhaarNo: digitsString(12, 'Aadhaar number must be exactly 12 digits'),
  panNo: z.string().regex(/^[A-Z]{5}\d{4}[A-Z]$/i, 'Enter a valid PAN number'),
  rc: optionalString(50),
  principalEmployerName: optionalString(30),
  principalEmployerAddress: optionalString(),
  wcPolicyNo: optionalString(50),
  wcStartDate: optionalDate(),
  wcExpiryDate: optionalDate(),
  serviceType: optionalString(100),
  serviceTaxNo: optionalString(50),
  shopActLicenseNo: optionalString(50),
  shopActExpiryDate: optionalDate(),
  labourLicenseNo: optionalString(50),
  labourLicenseStart: optionalDate(),
  labourLicenseExpiry: optionalDate(),
  bocwNo: optionalString(50),
  bocwStartDate: optionalDate(),
  bocwExpiryDate: optionalDate(),
  rcCount: optionalInt(),
  pfEstablishmentCode: optionalDigitsString(20, 'PF establishment code must be digits only'),
  esicEstablishmentCode: optionalDigitsString(20, 'ESIC establishment code must be digits only'),
  mlwfNo: optionalDigitsString(20, 'MLWF number must be digits only'),
  ptecNo: optionalDigitsString(20, 'PTEC number must be digits only'),
  ptrcNo: optionalDigitsString(20, 'PTRC number must be digits only'),
  buildingName: optionalString(30),
  status: z.enum(['ACTIVE', 'INACTIVE', 'BLACKLISTED']).optional(),
  password: optionalPassword(),
});

module.exports = { contractorSchema };
