const { z } = require('zod');
const { optionalString, optionalDate, optionalInt } = require('./common');

const workerSchema = z.object({
  firstName: z.string().min(1, 'First name is required').max(100),
  middleName: optionalString(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  dob: z.coerce.date({ errorMap: () => ({ message: 'Date of birth is required' }) }),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER'], { errorMap: () => ({ message: 'Select a gender' }) }),
  maritalStatus: optionalString(30),
  mobileNo: z.string().min(10, 'Enter a valid mobile number').max(15),
  permanentAddress: z.string().min(1, 'Permanent address is required'),
  currentAddress: optionalString(),
  city: optionalString(100),
  district: optionalString(100),
  state: optionalString(100),
  pincode: optionalString(10),
  contractorId: z.string().min(1, 'Contractor is required'),
  designationId: z.string().min(1, 'Designation is required'),
  labourCategoryId: z.string().min(1, 'Labour category is required'),
  idType: z.enum(['AADHAAR', 'PAN', 'VOTER_ID'], { errorMap: () => ({ message: 'Select an ID type' }) }),
  idNumber: z.string().min(1, 'ID number is required').max(50),
  bocwRegistrationNo: optionalString(50),
  bocwIssueDate: optionalDate(),
  bocwValidDate: optionalDate(),
  pfNumber: optionalString(50),
  uanNumber: optionalString(50),
  esicNumber: optionalString(50),
  panNumber: optionalString(20),
  ipNumber: optionalString(50),
  policeVerified: z.preprocess((v) => v === 'true' || v === true, z.boolean()).optional(),
  joinDate: z.coerce.date({ errorMap: () => ({ message: 'Join date is required' }) }),
  bankName: optionalString(100),
  bankBranch: optionalString(100),
  accountNo: optionalString(30),
  ifscCode: optionalString(15),
  nomineeName: optionalString(150),
  nomineeRelation: optionalString(50),
  nomineeChildrenCount: optionalInt(),
  nomineeQualification: optionalString(100),
  nomineeMobile: optionalString(15),
  sector: optionalString(100),
  status: z.enum(['ACTIVE', 'INACTIVE', 'BLACKLISTED']).optional(),
});

module.exports = { workerSchema };
