const { z } = require('zod');
const { optionalString, optionalDate, optionalInt, digitsString, optionalDigitsString, optionalExactDigitsString } = require('./common');

const workerSchema = z.object({
  firstName: z.string().min(1, 'First name is required').max(100),
  middleName: optionalString(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  fatherOrHusbandName: optionalString(150),
  dob: z.coerce.date({ errorMap: () => ({ message: 'Date of birth is required' }) }),
  gender: z.enum(['MALE', 'FEMALE', 'OTHER'], { errorMap: () => ({ message: 'Select a gender' }) }),
  maritalStatus: optionalString(30),
  mobileNo: digitsString(10, 'Mobile number must be exactly 10 digits'),
  permanentAddress: z.string().min(1, 'Permanent address is required'),
  currentAddress: optionalString(),
  village: optionalString(100),
  taluka: optionalString(100),
  city: optionalString(100),
  district: optionalString(100),
  state: optionalString(100),
  pincode: optionalExactDigitsString(6, 'Pincode must be exactly 6 digits'),
  contractorId: z.string().min(1, 'Contractor is required'),
  designationId: z.string().min(1, 'Designation is required'),
  labourCategoryId: z.string().min(1, 'Labour category is required'),
  idType: z.enum(['AADHAAR', 'PAN', 'VOTER_ID'], { errorMap: () => ({ message: 'Select an ID type' }) }),
  idNumber: z.string().min(1, 'ID number is required').max(50),
  bocwRegistrationNo: optionalString(50),
  bocwIssueDate: optionalDate(),
  bocwValidDate: optionalDate(),
  pfNumber: optionalDigitsString(20, 'PF number must be digits only'),
  uanNumber: optionalExactDigitsString(12, 'UAN number must be exactly 12 digits'),
  esicNumber: optionalDigitsString(17, 'ESIC number must be digits only'),
  panNumber: optionalString(20),
  ipNumber: optionalDigitsString(10, 'IP number must be digits only'),
  policeVerified: z.preprocess((v) => v === 'true' || v === true, z.boolean()).optional(),
  joinDate: z.coerce.date({ errorMap: () => ({ message: 'Join date is required' }) }),
  bankName: optionalString(100),
  bankBranch: optionalString(100),
  accountNo: optionalDigitsString(18, 'Account number must be digits only'),
  ifscCode: optionalString(15),
  nomineeName: optionalString(150),
  nomineeRelation: optionalString(50),
  nomineeChildrenCount: optionalInt(),
  nomineeQualification: optionalString(100),
  nomineeMobile: optionalExactDigitsString(10, 'Nominee mobile number must be exactly 10 digits'),
  sector: optionalString(100),
  status: z.enum(['ACTIVE', 'INACTIVE', 'BLACKLISTED']).optional(),
});

module.exports = { workerSchema };
